apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: database
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.volumeBasePath }}/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: ''
  selector:
    matchLabels:
      type: database
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
        - name: database
          image: postgres:17.5
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
