---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: avatars-pv
  labels:
    type: avatars
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '{{ .Values.volumeBasePath }}/avatars'
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avatars-pvc
spec:
  storageClassName: ''
  selector:
    matchLabels:
      type: avatars
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'chat-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: database-url-secret
        - name: avatars-volume
          persistentVolumeClaim:
            claimName: avatars-pvc
      containers:
        - name: chat-api
          image: '{{ .Values.images.backend.name }}:{{ .Values.images.backend.version }}'
          command:
            - bash
            - -c
            - 'node dist/main.js'
          volumeMounts:
            - name: avatars-volume
              mountPath: /usr/app/avatars
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: database-url-secret
          readinessProbe:
            httpGet:
              path: /app/debug
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api
spec:
  type: NodePort
  selector:
    app: chat-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
