apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chat-api
                port:
                  number: 3000
          - path: /adminer
            pathType: Prefix
            backend:
              service:
                name: adminer
                port:
                  number: 8080
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: chat-api
                port:
                  number: 3000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls:
    - secretName: chat-tls
      hosts:
        - {{ .Values.host }}
