apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: '{{ .Values.secrets.DB_PASS }}'
  POSTGRES_USER: '{{ .Values.secrets.DB_USER }}'
  POSTGRES_DB: '{{ .Values.secrets.DB }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: database-url-secret
type: Opaque
stringData:
  DATABASE_URL: 'db'
  DATABASE_PW: '{{ .Values.secrets.DB_PASS }}'
  JWT_SECRET: '{{ .Values.secrets.JWT_SECRET }}'
  SALT: '{{ .Values.secrets.SALT}}'
